name: CI/CD pipeline

on:
  push: 
    branches:
      - release/*
      - main

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: docker build
        run: |
          docker build -t davejfranco/oci-action-api .

  release:
    runs-on: ubuntu-latest
    needs: build-docker
    steps: 
      - name: Get Release version
        if: github.ref == 'refs/heads/release/*'
        id: release_version
        run: |
          echo "RELEASE=$(echo ${GITHUB_HEAD_REF} | cut -d'/' -f4)" >> $GITHUB_ENV
          echo $RELEASE_VERSION

    
    # - name: Print release
    #   run: |
    #     echo $RELEASE_VERSION
    #     echo ${{ env.RELEASE_VERSION }}
    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5.5
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Create a GitHub release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.tag_version.outputs.new_tag }}
    #     release_name: Release ${{ steps.tag_version.outputs.new_tag }}
    #     body: ${{ steps.tag_version.outputs.changelog }}

