name: CI/CD pipeline

on:
  push: 
    branches:
      - main   
  pull_request:
    types: [closed]
    branches:
      - master
    
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: tonynguyenit18/github-action-custom-vars@v1
      - run: echo $RECENT_MERGED_BRANCH_NAME

      - run: echo $RECENT_MERGED_BRANCH_NAME

      - name: Get Release version
        id: release_version
        if: github.ref == 'refs/heads/main' #startsWith(github.head_ref, 'refs/heads/release')
        run: |

          if [[ $RECENT_MERGED_BRANCH_NAME =~ "release" ]]; then
            export RELEASE_VERSION=$(echo $RECENT_MERGED_BRANCH_NAME | cut -d'/' -f2)
            echo ::set-output name=version::$RELEASE_VERSION #echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
            echo "$RELEASE_VERSION"
          fi

      - name: Create tag
        if: steps.release_version.outputs.version
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.release_version.outputs.version }}",
              sha: context.sha
            })

      - name: Create a GitHub release
        if: steps.release_version.outputs.version
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $RELEASE_VERSION
          release_name: "Release ${{ steps.release_version.outputs.version }}"

  #comment
  # build-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: docker build
  #       run: |
  #         docker build -t davejfranco/oci-action-api .
    
    # - name: Print release
    #   run: |
    #     echo $RELEASE_VERSION
    #     echo ${{ env.RELEASE_VERSION }}
    

