name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'namespace tu run command'
        required: true
      command:
        description: 'the actual command'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          which aws
          which kubectl